services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./php:/var/www/html
    ports:
      - "8083:80"
    depends_on:
      - mysql
      - mongo

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookshare
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - mysql

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:

